# Generated by Django 3.2.25 on 2024-06-06 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('writer', models.CharField(max_length=10, verbose_name='작성자')),
                ('category', models.CharField(choices=[('DAIRY', '일기'), ('STUDY', '공부'), ('ETC', '기타')], max_length=20)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='', verbose_name='썸네일')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('commenter', models.CharField(max_length=10, verbose_name='댓글작성자')),
                ('comment', models.TextField(max_length=500, verbose_name='댓글내용')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
