# Generated by Django 3.2.25 on 2024-06-07 22:14

from django.db import migrations, models
import posts.validators


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.URLField(blank=True, null=True, validators=[posts.validators.unvalidate_file_extension], verbose_name='썸네일'),
        ),
    ]
