# Generated by Django 3.2.25 on 2024-06-08 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_thumbnail_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='thumbnail_url',
        ),
    ]
