# Generated by Django 3.2.25 on 2024-05-11 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_remove_post_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='writer',
            field=models.CharField(default=2, max_length=10, verbose_name='작성자'),
            preserve_default=False,
        ),
    ]
