# Generated by Django 5.0.6 on 2024-05-12 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guestbook',
            old_name='gusetbook_id',
            new_name='id',
        ),
    ]
